### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review 

### ISSUE THREAD

**Issue by bfxzyn** [bfxzyn/AndroidApps#1]
My simple todo app is complete, please help to review it.  
I'm trying to use ActiveAndroid and follow <a href="https://github.com/pardom/ActiveAndroid/wiki/Getting-started"> instruction1</a> and <a href="http://slidenerd.com/2014/09/10/tutorial-5-android-database-without-sqlite-code-using-activeandroid-library/">instruction2</a>, but I always hit the issue that "no such table: Item". I tried the method in that instruction's comment but it won't help me to solve the issue. /cc @codepathreview @codepath

**Comment by bfxzyn** [comment]
The error message:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.meiyiyou.simpletodo, PID: 6711
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.meiyiyou.simpletodo/com.meiyiyou.simpletodo.MainActivity}: android.database.sqlite.SQLiteException: no such table: Item (code 1): , while compiling: SELECT ALL * FROM Item
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                        Caused by: android.database.sqlite.SQLiteException: no such table: Item (code 1): , while compiling: SELECT ALL * FROM Item
                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                           at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                                           at com.activeandroid.Model.rawQuery(Model.java:349)
                                                                           at com.activeandroid.query.From.execute(From.java:155)
                                                                           at com.meiyiyou.simpletodo.MainActivity.showAllItems(MainActivity.java:125)
                                                                           at com.meiyiyou.simpletodo.MainActivity.onCreate(MainActivity.java:40)
                                                                           at android.app.Activity.performCreate(Activity.java:5990)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by nesquena** [comment]
> I'm trying to use ActiveAndroid and follow instruction1 and instruction2, but I always hit the issue that "no such table: Item". I tried the method in that instruction's comment but it won't help me to solve the issue. 

Please refer instead to our [ActiveAndroid guide here](http://guides.codepath.com/android/ActiveAndroid-Guide#common-questions). This should allow you to solve any issues.

**Comment by nesquena** [comment]
Yineng,

Oh and the basic project looks good. This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work. 

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by bfxzyn** [comment]
Thanks for helping. The ActiveAndroid issue is solved and works fine now.
CR: https://github.com/bfxzyn/AndroidApps/commit/7eb36698e50094ecd48b441974414c9f3e462fde

**Comment by bfxzyn** [comment]
Adding new features:
1. Persist the todo items into SQLite instead of a text file 
2. Improve style of the todo items in the list using a custom adapter
3. Add support for completion due dates for todo items (and display within listview item)
4. Add support for selecting the priority of each todo item (and display in listview item)
Please review the new gif demo. 
/cc @codepathreview @codepath

**Comment by nesquena** [comment]
Great to see you were able to augment your app with a few extension tasks now. As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

We'll be in touch with you again soon via email. Let me know if you have any questions about the project or anything in the meantime.
